### ISSUE TITLE
path issue

### ISSUE THREAD

**Issue by jabra-vilas** [colynb/gulp-data#12]
Shouldn't it be  path.basename(file.path,'.html') instead of  path.basename(file.path)?

Error: Error: Cannot find module './app/templates/index.html.json'

**Comment by DusanMilko** [comment]
Even after switching to 
path.basename(file.path,'.hbs') + '.json'
it still cannot find module, any solutions?

**Comment by brunowego** [comment]
+1

**Comment by colynb** [comment]
This isn't an issue with gulp-data. The README provides some suggestions for how to use gulp-data with JSON files but its up to you how you want to import them. It's hard to know what the problem is in your particular case since I don't know where your json files are relative to the gulp file. I would try requiring a json file in your gulp file without using gulp-data, and see if you can get it to load.
